node{
  agent any
  stages{
    
    stage('test'){
      steps{
      echo "Testing stage.";
      }
    }
    stage('cleantest'){
      steps{
      echo "buikding stage"
        echo "maven clean test through pipeline.. ";
    }
  }
}
